stages:
  - build
  - test
  - build image

build:
  stage: build
  image: node:16-alpine
  script:
    - npm install

build test:
  stage: test
  image: node:16-alpine
  before_script:
    - npm install
    - apk add --no-cache curl
  script:
    - npm run lint
    - npm run test
    - npm run dev &
    - timeout 60 watch -n 1 -g 'curl -LIs http://localhost:8000 |grep -q "200 OK" && echo "Service responded 200 OK"'

build image:
  stage: build image
  script:
    - docker --version
    - docker ps
