stages:
  - build
  - test
  - build image

variables:
  PROJECT_NAME: buketti-backend
  CONTAINER_REGISTRY: registry.gitlab.valtori.fi/vm-private/buketti-backend

build:
  stage: build
  image: node:16-alpine
  before_script:
    - node -v
    - npm -v
  script:
    - npm install

test build:
  stage: test
  image: node:16-alpine
  before_script:
    - node -v
    - npm -v
    - npm install
    - apk add --no-cache curl
  script:
    - npm run lint
    #- npm run test
    - npm run dev &
    - timeout 60 sh -c -- 'until curl -LIs http://localhost:8000 |grep -q "200 OK" && echo "Server responded 200 OK" ; do sleep 1 ; done'

build image:
  stage: build image
  before_script:
    - docker -v
  script:
    - docker build -t ${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker image tag ${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_REGISTRY}/${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
    - docker image push ${CONTAINER_REGISTRY}/${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
