version: '2.4'
services:
  web:
    build: .
    command: npm run docker
    environment:
      - DB_SCHEMA=${DB_SCHEMA:-public}
      - DB_USER=${DB_USER:-testuser}
      - DB_PASSWORD=${DB_PASSWORD:-testpasswd}
      - DB_HOST=${DB_HOST:-postgres}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=${DB_USER:-testuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-testpasswd}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-youremail@email.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-yourpassword}
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    restart: always
