version: '2.4'
services:
  web:
    build: .
    command: npm run docker
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpasswd
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL:${PGADMIN_DEFAULT_EMAIL:-youremail@email.com}
      - PGADMIN_DEFAULT_PASSWORD=yourpassword
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    restart: always
