version: '2.4'
services:
  web:
    build: .
    command: sh -c "npm run migrate deploy && npm run dev"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-testuser}:${DB_PASSWORD:-testpasswd}@postgres:${DB_PORT:-5432}/${DB_NAME:-postgres}?schema=${DB_SCHEMA:-public}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
      - "./nodemon.json:/usr/app/nodemon.json"
    restart: always
    depends_on:
      - postgres


  postgres:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=${DB_USER:-testuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-testpasswd}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-youremail@email.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-yourpassword}
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    restart: always
    depends_on:
      - postgres
